@EventsAPI_HostAddress = https://localhost:7193

GET {{EventsAPI_HostAddress}}/weatherforecast/
Accept: application/json


###
POST {{EventsAPI_HostAddress}}/login
Content-Type: application/json

{
  "email": "string@string.com",
  "password": "String1!",
  "twoFactorCode": "string",
  "twoFactorRecoveryCode": "string"
}
